name: 'GitHub issue forms parser'
description: 'Parses a GitHub issue form body and outputs a JSON representation.'
branding:
  icon: align-justify
  color: blue
inputs:
  template-filepath:
    description: 'The filepath for the GitHub issue form template.'
    required: true
  issue-form-body:
    description: 'The issue form body.'
    required: true
outputs:
  parsed-issue:
    description: 'The parsed issue form as a JSON string.'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/edumserrano/github-issue-forms-parser:latest'
  args:
    - parse-issue-form
    - --template-filepath
    - ${{ inputs.template-filepath }}
    - --issue-body
    - ${{ inputs.issue-form-body }}
