global using System.Text.Json;
global using System.Text.Json.Serialization;
global using CliFx.Exceptions;
global using CliFx.Infrastructure;
global using GitHubIssuesParserCli.CliCommands.ParseIssueForm;
global using GitHubIssuesParserCli.IssueFormBody.Parsing;
global using GitHubIssuesParserCli.IssueFormTemplates.Parsing;
global using GitHubIssuesParserCli.Tests.Auxiliary;
global using Shouldly;
global using Xunit;
global using static GitHubIssuesParserCli.Tests.Auxiliary.NewLines;
